import random

# Lista de nomes de épocas dos dinossauros
epocas_dinossauros = [
    "Triássico",
    "Jurássico",
    "Cretáceo",
    "Período Carniano",
    "Período Noriano",
    "Período Rhaetiano",
    "Período Hettangiano",
    "Período Sinemuriano",
    "Período Pliensbachiano",
    "Período Toarciano",
    "Período Aaleniano",
    "Período Bajociano",
    "Período Bathoniano",
    "Período Calloviano",
    "Período Oxfordiano",
    "Período Kimmeridgiano",
    "Período Tithoniano",
    "Período Berriasiano",
    "Período Valanginiano",
    "Período Hauteriviano",
    "Período Barremiano",
    "Período Aptiano",
    "Período Albiano",
    "Período Cenomaniano",
    "Período Turoniano",
    "Período Coniaciano",
    "Período Santoniano",
    "Período Campaniano",
    "Período Maestrichtiano",
    "Período Daniano",
    "Período Selandiano",
    "Período Thanetiano",
    "Período Ypresiano",
    "Período Lutetiano",
    "Período Bartoniano",
    "Período Priaboniano",
    "Período Rupeliano",
    "Período Chattiano",
    "Período Aquitaniano",
    "Período Burdigaliano",
    "Período Langhiano",
    "Período Serravalliano",
    "Período Tortoniano",
    "Período Messiniano",
    "Período Zancliano",
    "Período Piacenziano",
    "Período Gelasiano",
    "Período Calabriano",
    "Período Chibaniano",
    "Período Etapiano",
    "Período Priaboniano",
    "Período Rupeliano",
    "Período Chattiano",
    "Período Aquitaniano",
    "Período Burdigaliano",
    "Período Langhiano",
    "Período Serravalliano",
    "Período Tortoniano",
    "Período Messiniano",
    "Período Zancliano",
    "Período Piacenziano",
    "Período Gelasiano",
    "Período Calabriano",
    "Período Chibaniano",
    "Período Etapiano",
    "Período Gelasiano",
    "Período Calabriano",
    "Período Chibaniano",
    "Período Etapiano",
    "Período Priaboniano",
    "Período Rupeliano",
    "Período Chattiano",
    "Período Aquitaniano",
    "Período Burdigaliano",
    "Período Langhiano",
    "Período Serravalliano",
    "Período Tortoniano",
    "Período Messiniano",
    "Período Zancliano",
    "Período Piacenziano",
    "Período Gelasiano",
    "Período Calabriano",
    "Período Chibaniano",
    "Período Etapiano",
    "Período Gelasiano",
    "Período Calabriano",
    "Período Chibaniano",
    "Período Etapiano",
    "Período Gelasiano",
    "Período Calabriano",
    "Período Chibaniano",
    "Período Etapiano",
    "Período Gelasiano",
    "Período Calabriano",
    "Período Chibaniano",
    "Período Etapiano",
    "Período Gelasiano",
    "Período Calabriano",
    "Período Chibaniano",
    "Período Etapiano",
    "Período Gelasiano",
    "Período Calabriano",
    "Período Chibaniano",
    "Período Etapiano",
    "Período Priaboniano",
    "Período Rupeliano",
    "Período Chattiano",
    "Período Aquitaniano",
    "Período Burdigaliano",
    "Período Langhiano",
    "Período Serravalliano",
    "Período Tortoniano",
    "Período Messiniano",
    "Período Zancliano",
    "Período Piacenziano",
    "Período Gelasiano",
    "Período Calabriano",
    "Período Chibaniano",
    "Período Etapiano",
]

# Dicionário para armazenar a geração de cada nome de época dos dinossauros
geracoes_por_epoca = {}

# Gerar gerações aleatórias para cada época dos dinossauros
for epoca in epocas_dinossauros:
    geracoes_por_epoca[epoca] = random.randint(0, 100)

# Exibir o dicionário de gerações por época
print("Gerações por época dos dinossauros:")
for epoca, geracao in geracoes_por_epoca.items():
    print(f"{epoca}: Geração {geracao}")
